version: '2'
services:

  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - .php/code:/code

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  allowlist-reload:
    image: magnuscolors/allowlist-reload
    container_name: allowlist-reload
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
      - .php/code:/code

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

  php:
    image: php:7-fpm
    container_name: php
    restart: unless-stopped
    volumes:
      - .php/code:/code
    environment:
      - VIRTUAL_HOST=keyportal
      - VIRTUAL_PORT=80
      - KEYPORTAL=true

  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: postgres:9.6
    restart: unless-stopped
    volumes:
      - .db/data/:/var/lib/postgresql/data
      - .db/socket/:/var/run/postgresql/
    ports:
      - 5432:5432

  odoo:
    build:
      context: .
      dockerfile: Dockerfile-prod
      args:
        - AK_ENV=prod
    restart: unless-stopped
    expose:
      - 8069
      - 8072
    environment:
      - AK_ENV=prod # TODO avoid repetition
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=8069,8072/longpolling
      - ALLOWLIST=true
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
      - .db/socket/:/var/run/postgresql/
      - ./data:/home/odoo/data
    labels:
      main_service: "True"